### ISSUE TITLE
pa_fields_conv won't install with OCaml 4.03

### ISSUE THREAD

**Issue by jstolarek** [janestreet/pa_fields_conv#1]
Just tried installing `pa_fields_conv` using 4.03.0 switch and got this:

```
[killy@xerxes : ~] opam install pa_fields_conv
[ERROR] pa_fields_conv is not available because your system doesn't comply with ocaml-version >= "4.00.0" & ocaml-version < "4.03".
```

**Comment by bmillwood** [comment]
Sounds right. You probably want ppx_fields_conv instead.

**Comment by jstolarek** [comment]
Indeed - `ppx_fields_conv` does what I wanted. So `pa_fields_conv` is not intended to work with 4.03?

**Comment by trefis** [comment]
> So pa_fields_conv is not intended to work with 4.03?

No.
